unit EDSDKERRORS;
{**************************************************************************}
{                                                                          }
{    This C DLL header file first (automatic) conversion generated by:     }
{    HeadConv 4.0 (c) 2000 by Bob Swart (aka Dr.Bob - www.drbob42.com)     }
{      Final Delphi-Jedi (Darth) command-line units edition                }
{                                                                          }
{    Generated Date: 2006-06-16                                            }
{    Generated Time: 22:04:40                                              }
{                                                                          }
{**************************************************************************}

interface

{$IFDEF MSWINDOWS}
uses Windows, Wintypes, WinProcs;
{$ENDIF}

{=> c:\ed-sdk v1.1\edsdk\header\EDSDKERRORS.H <=}

{+//***************************************************************************** }
{-** }
{-* PROJECT : EOS Digital Software Development Kit EDSDK* }
{-* NAME : EDSDKErros.h* }
{-** }
{-* Description: ERROR DEFINITION FOR EDSDK* }
{-** }
{-******************************************************************************* }
{-** }
{-* Written and developed by Camera Design Dept.53* }
{-* Copyright Canon Inc. 2006 All Rights Reserved* }
{-** }
{-******************************************************************************* }
{-* File Update Information:* }
{-* DATE Identify Comment* }
{-* -----------------------------------------------------------------------* }
{-* 06-03-16 F-001 create first version.* }
{-** }
{=***************************************************************************** }

{+//----------------------------------------------------------------------------*/ }

{+//***************************************************************************** }
{-Definition of error Codes }
{=***************************************************************************** }
{+//----------------------------------------------------------------------- }
{-ED-SDK Error Code Masks }
{=------------------------------------------------------------------------ }
const
  EDS_ISSPECIFIC_MASK = $80000000;
const
  EDS_COMPONENTID_MASK = $7F000000;
const
  EDS_RESERVED_MASK = $00FF0000;
const
  EDS_ERRORID_MASK = $0000FFFF;

{+//----------------------------------------------------------------------- }
{-ED-SDK Base Component IDs }
{=------------------------------------------------------------------------ }
const
  EDS_CMP_ID_CLIENT_COMPONENTID = $01000000;
const
  EDS_CMP_ID_LLSDK_COMPONENTID = $02000000;
const
  EDS_CMP_ID_HLSDK_COMPONENTID = $03000000;

{+//----------------------------------------------------------------------- }
{-ED-SDK Functin Success Code }
{=------------------------------------------------------------------------ }
const
  EDS_ERR_OK = $00000000;

{+//----------------------------------------------------------------------- }
{-ED-SDK Generic Error IDs }
{=------------------------------------------------------------------------ }
{+// Miscellaneous errors*/ }
const
  EDS_ERR_UNIMPLEMENTED = $00000001;
const
  EDS_ERR_INTERNAL_ERROR = $00000002;
const
  EDS_ERR_MEM_ALLOC_FAILED = $00000003;
const
  EDS_ERR_MEM_FREE_FAILED = $00000004;
const
  EDS_ERR_OPERATION_CANCELLED = $00000005;
const
  EDS_ERR_INCOMPATIBLE_VERSION = $00000006;
const
  EDS_ERR_NOT_SUPPORTED = $00000007;
const
  EDS_ERR_UNEXPECTED_EXCEPTION = $00000008;
const
  EDS_ERR_PROTECTION_VIOLATION = $00000009;
const
  EDS_ERR_MISSING_SUBCOMPONENT = $0000000A;
const
  EDS_ERR_SELECTION_UNAVAILABLE = $0000000B;

{+// File errors*/ }
const
  EDS_ERR_FILE_IO_ERROR = $00000020;
const
  EDS_ERR_FILE_TOO_MANY_OPEN = $00000021;
const
  EDS_ERR_FILE_NOT_FOUND = $00000022;
const
  EDS_ERR_FILE_OPEN_ERROR = $00000023;
const
  EDS_ERR_FILE_CLOSE_ERROR = $00000024;
const
  EDS_ERR_FILE_SEEK_ERROR = $00000025;
const
  EDS_ERR_FILE_TELL_ERROR = $00000026;
const
  EDS_ERR_FILE_READ_ERROR = $00000027;
const
  EDS_ERR_FILE_WRITE_ERROR = $00000028;
const
  EDS_ERR_FILE_PERMISSION_ERROR = $00000029;
const
  EDS_ERR_FILE_DISK_FULL_ERROR = $0000002A;
const
  EDS_ERR_FILE_ALREADY_EXISTS = $0000002B;
const
  EDS_ERR_FILE_FORMAT_UNRECOGNIZED = $0000002C;
const
  EDS_ERR_FILE_DATA_CORRUPT = $0000002D;
const
  EDS_ERR_FILE_NAMING_NA = $0000002E;

{+// Directory errors*/ }
const
  EDS_ERR_DIR_NOT_FOUND = $00000040;
const
  EDS_ERR_DIR_IO_ERROR = $00000041;
const
  EDS_ERR_DIR_ENTRY_NOT_FOUND = $00000042;
const
  EDS_ERR_DIR_ENTRY_EXISTS = $00000043;
const
  EDS_ERR_DIR_NOT_EMPTY = $00000044;

{+// Property errors*/ }
const
  EDS_ERR_PROPERTIES_UNAVAILABLE = $00000050;
const
  EDS_ERR_PROPERTIES_MISMATCH = $00000051;
const
  EDS_ERR_PROPERTIES_NOT_LOADED = $00000053;

{+// Function Parameter errors*/ }
const
  EDS_ERR_INVALID_PARAMETER = $00000060;
const
  EDS_ERR_INVALID_HANDLE = $00000061;
const
  EDS_ERR_INVALID_POINTER = $00000062;
const
  EDS_ERR_INVALID_INDEX = $00000063;
const
  EDS_ERR_INVALID_LENGTH = $00000064;
const
  EDS_ERR_INVALID_FN_POINTER = $00000065;
const
  EDS_ERR_INVALID_SORT_FN = $00000066;

{+// Device errors*/ }
const
  EDS_ERR_DEVICE_NOT_FOUND = $00000080;
const
  EDS_ERR_DEVICE_BUSY = $00000081;
const
  EDS_ERR_DEVICE_INVALID = $00000082;
const
  EDS_ERR_DEVICE_EMERGENCY = $00000083;
const
  EDS_ERR_DEVICE_MEMORY_FULL = $00000084;
const
  EDS_ERR_DEVICE_INTERNAL_ERROR = $00000085;
const
  EDS_ERR_DEVICE_INVALID_PARAMETER = $00000086;
const
  EDS_ERR_DEVICE_NO_DISK = $00000087;
const
  EDS_ERR_DEVICE_DISK_ERROR = $00000088;
const
  EDS_ERR_DEVICE_CF_GATE_CHANGED = $00000089;
const
  EDS_ERR_DEVICE_DIAL_CHANGED = $0000008A;
const
  EDS_ERR_DEVICE_NOT_INSTALLED = $0000008B;
const
  EDS_ERR_DEVICE_STAY_AWAKE = $0000008C;
const
  EDS_ERR_DEVICE_NOT_RELEASED = $0000008D;

{+// Stream errors*/ }
const
  EDS_ERR_STREAM_IO_ERROR = $000000A0;
const
  EDS_ERR_STREAM_NOT_OPEN = $000000A1;
const
  EDS_ERR_STREAM_ALREADY_OPEN = $000000A2;
const
  EDS_ERR_STREAM_OPEN_ERROR = $000000A3;
const
  EDS_ERR_STREAM_CLOSE_ERROR = $000000A4;
const
  EDS_ERR_STREAM_SEEK_ERROR = $000000A5;
const
  EDS_ERR_STREAM_TELL_ERROR = $000000A6;
const
  EDS_ERR_STREAM_READ_ERROR = $000000A7;
const
  EDS_ERR_STREAM_WRITE_ERROR = $000000A8;
const
  EDS_ERR_STREAM_PERMISSION_ERROR = $000000A9;
const
  EDS_ERR_STREAM_COULDNT_BEGIN_THREAD = $000000AA;
const
  EDS_ERR_STREAM_BAD_OPTIONS = $000000AB;
const
  EDS_ERR_STREAM_END_OF_STREAM = $000000AC;

{+// Communications errors*/ }
const
  EDS_ERR_COMM_PORT_IS_IN_USE = $000000C0;
const
  EDS_ERR_COMM_DISCONNECTED = $000000C1;
const
  EDS_ERR_COMM_DEVICE_INCOMPATIBLE = $000000C2;
const
  EDS_ERR_COMM_BUFFER_FULL = $000000C3;
const
  EDS_ERR_COMM_USB_BUS_ERR = $000000C4;

{+// Lock/Unlock*/ }
const
  EDS_ERR_USB_DEVICE_LOCK_ERROR = $000000D0;
const
  EDS_ERR_USB_DEVICE_UNLOCK_ERROR = $000000D1;

{+// STI/WIA*/ }
const
  EDS_ERR_STI_UNKNOWN_ERROR = $000000E0;
const
  EDS_ERR_STI_INTERNAL_ERROR = $000000E1;
const
  EDS_ERR_STI_DEVICE_CREATE_ERROR = $000000E2;
const
  EDS_ERR_STI_DEVICE_RELEASE_ERROR = $000000E3;
const
  EDS_ERR_DEVICE_NOT_LAUNCHED = $000000E4;

const
  EDS_ERR_ENUM_NA = $000000F0;
const
  EDS_ERR_INVALID_FN_CALL = $000000F1;
const
  EDS_ERR_HANDLE_NOT_FOUND = $000000F2;
const
  EDS_ERR_INVALID_ID = $000000F3;
const
  EDS_ERR_WAIT_TIMEOUT_ERROR = $000000F4;

{+// PTP*/ }
const
  EDS_ERR_SESSION_NOT_OPEN = $00002003;
const
  EDS_ERR_INVALID_TRANSACTIONID = $00002004;
const
  EDS_ERR_INCOMPLETE_TRANSFER = $00002007;
const
  EDS_ERR_INVALID_STRAGEID = $00002008;
const
  EDS_ERR_DEVICEPROP_NOT_SUPPORTED = $0000200A;
const
  EDS_ERR_INVALID_OBJECTFORMATCODE = $0000200B;
const
  EDS_ERR_SELF_TEST_FAILED = $00002011;
const
  EDS_ERR_PARTIAL_DELETION = $00002012;
const
  EDS_ERR_SPECIFICATION_BY_FORMAT_UNSUPPORTED = $00002014;
const
  EDS_ERR_NO_VALID_OBJECTINFO = $00002015;
const
  EDS_ERR_INVALID_CODE_FORMAT = $00002016;
const
  EDS_ERR_UNKNOWN_VENDER_CODE = $00002017;
const
  EDS_ERR_CAPTURE_ALREADY_TERMINATED = $00002018;
const
  EDS_ERR_PTP_DEVICE_BUSY = $00002019;

const
  EDS_ERR_INVALID_PARENTOBJECT = $0000201A;
const
  EDS_ERR_INVALID_DEVICEPROP_FORMAT = $0000201B;
const
  EDS_ERR_INVALID_DEVICEPROP_VALUE = $0000201C;
const
  EDS_ERR_SESSION_ALREADY_OPEN = $0000201E;
const
  EDS_ERR_TRANSACTION_CANCELLED = $0000201F;
const
  EDS_ERR_SPECIFICATION_OF_DESTINATION_UNSUPPORTED = $00002020;
const
  EDS_ERR_NOT_CAMERA_SUPPORT_SDK_VERSION = $00002021;

// PTP_Vendor
const
  EDS_ERR_UNKNOWN_COMMAND = $0000A001;
const
  EDS_ERR_OPERATION_REFUSED = $0000A005;
const
  EDS_ERR_LENS_COVER_CLOSE = $0000A006;
const
  EDS_ERR_LOW_BATTERY	= $0000A101;
const
  EDS_ERR_OBJECT_NOTREADY = $0000A102;
const
  EDS_ERR_CANNOT_MAKE_OBJECT = $0000A104;
const
  EDS_ERR_MEMORYSTATUS_NOTREADY = $0000A106;

// Take Picture errors
const
  EDS_ERR_TAKE_PICTURE_AF_NG = $00008D01;
const
  EDS_ERR_TAKE_PICTURE_RESERVED = $00008D02;
const
  EDS_ERR_TAKE_PICTURE_MIRROR_UP_NG = $00008D03;
const
  EDS_ERR_TAKE_PICTURE_SENSOR_CLEANING_NG = $00008D04;
const
  EDS_ERR_TAKE_PICTURE_SILENCE_NG = $00008D05;
const
  EDS_ERR_TAKE_PICTURE_NO_CARD_NG = $00008D06;
const
  EDS_ERR_TAKE_PICTURE_CARD_NG = $00008D07;
const
  EDS_ERR_TAKE_PICTURE_CARD_PROTECT_NG = $00008D08;
const
  EDS_ERR_TAKE_PICTURE_MOVIE_CROP_NG= $00008D09;
const
  EDS_ERR_TAKE_PICTURE_STROBO_CHARGE_NG	= $00008D0A;
const
  EDS_ERR_TAKE_PICTURE_NO_LENS_NG = $00008D0B;
const
  EDS_ERR_TAKE_PICTURE_SPECIAL_MOVIE_MODE_NG = $00008D0C;
const
  EDS_ERR_TAKE_PICTURE_LV_REL_PROHIBIT_MODE_NG = $00008D0D;

const
  EDS_ERR_LAST_GENERIC_ERROR_PLUS_ONE = $000000F5;

function GetErrorCodeString(ErrorCode : Longword) : string;

implementation

function GetErrorCodeString(ErrorCode : Longword) : string;
begin
  result := '';
  case (EDS_ERRORID_MASK and ErrorCode) of
    $00000001 : result := 'Unimplemented';
    $00000002 : result := 'Internal error';
    $00000003 : result := 'Memory allocation failed';
    $00000004 : result := 'Memory free failed';
    $00000005 : result := 'Operation cancelled';
    $00000006 : result := 'Incompatible version';
    $00000007 : result := 'Not supported';
    $00000008 : result := 'Unexpected exception';
    $00000009 : result := 'Protection violation';
    $0000000A : result := 'Mission subcomponent';
    $0000000B : result := 'Selection unavailable';
    $00000020 : result := 'File IO error';
    $00000021 : result := 'File too many open';
    $00000022 : result := 'File not found';
    $00000023 : result := 'File open error';
    $00000024 : result := 'File close error';
    $00000025 : result := 'File seek error';
    $00000026 : result := 'File tell error';
    $00000027 : result := 'File read error';
    $00000028 : result := 'File write error';
    $00000029 : result := 'File permission error';
    $0000002A : result := 'File disk full error';
    $0000002B : result := 'File already exists';
    $0000002C : result := 'File format unrecognized';
    $0000002D : result := 'File data corrupt';
    $0000002E : result := 'File naming not applicable';
    $00000040 : result := 'Directory not found';
    $00000041 : result := 'Directory IO error';
    $00000042 : result := 'Directory entry not found';
    $00000043 : result := 'Directory entry exists';
    $00000044 : result := 'Directory not empty';
    $00000050 : result := 'Properties unavailable';
    $00000051 : result := 'Properties mismatch';
    $00000053 : result := 'Properties not loaded';
    $00000060 : result := 'Invalid parameter';
    $00000061 : result := 'Invalid handle';
    $00000062 : result := 'Invalid pointer';
    $00000063 : result := 'Invalid index';
    $00000064 : result := 'Invalid length';
    $00000065 : result := 'Invalid function pointer';
    $00000066 : result := 'Invalid sort function';
    $00000080 : result := 'Device not found';
    $00000081 : result := 'Device busy';
    $00000082 : result := 'Device invalid';
    $00000083 : result := 'Device emergency';
    $00000084 : result := 'Device memory full';
    $00000085 : result := 'Device internal error';
    $00000086 : result := 'Device invalid parameter';
    $00000087 : result := 'Device no disk';
    $00000088 : result := 'Device disk error';
    $00000089 : result := 'Device CompactFlash gate changed';
    $0000008A : result := 'Device dial changed';
    $0000008B : result := 'Device not installed';
    $0000008C : result := 'Device stay awake';
    $0000008D : result := 'Device not released';
    $000000A0 : result := 'Stream IO error';
    $000000A1 : result := 'Stream not open';
    $000000A2 : result := 'Stream already open';
    $000000A3 : result := 'Stream open error';
    $000000A4 : result := 'Stream close error';
    $000000A5 : result := 'Stream seek error';
    $000000A6 : result := 'Stream tell error';
    $000000A7 : result := 'Stream read error';
    $000000A8 : result := 'Stream write error';
    $000000A9 : result := 'Stream permission error';
    $000000AA : result := 'Stream could not begin thread';
    $000000AB : result := 'Stream bad options';
    $000000AC : result := 'Stream end of stream';
    $000000C0 : result := 'Communication port in use';
    $000000C1 : result := 'Communication disconnected';
    $000000C2 : result := 'Communication device incompatible';
    $000000C3 : result := 'Communication buffer full';
    $000000C4 : result := 'Communication USB bus error';
    $000000D0 : result := 'USB device lock error';
    $000000D1 : result := 'USB device unlock error';
    $000000E0 : result := 'STI unknown error';
    $000000E1 : result := 'STI internal error';
    $000000E2 : result := 'STI device create error';
    $000000E3 : result := 'STI device release error';
    $000000E4 : result := 'STI device not launched';
    $000000F0 : result := 'Enum not applicable';
    $000000F1 : result := 'Invalid function call';
    $000000F2 : result := 'Handle not found';
    $000000F3 : result := 'Invalid ID';
    $000000F4 : result := 'Wait timeout error';
    $00002003 : result := 'PTP session not open';
    $00002004 : result := 'PTP invalid transaction id';
    $00002007 : result := 'PTP incomplete transfer';
    $00002008 : result := 'PTP invalid strage id';
    $0000200A : result := 'PTP device property not supported';
    $0000200B : result := 'PTP invalid object format code';
    $00002011 : result := 'PTP self test failed';
    $00002012 : result := 'PTP partial deletion';
    $00002014 : result := 'PTP specification by format unsupported';
    $00002015 : result := 'PTP no valid object info';
    $00002016 : result := 'PTP invalid code format';
    $00002017 : result := 'PTP unknown vender code';
    $00002018 : result := 'PTP capture already terminated';
    $00002019 : result := 'PTP device busy';
    $0000201A : result := 'PTP invalid parent object';
    $0000201B : result := 'PTP invalid device prop format';
    $0000201C : result := 'PTP invalid device prop value';
    $0000201E : result := 'PTP session already open';
    $0000201F : result := 'PTP transaction cancelled';
    $00002020 : result := 'PTP specification of destination unsupported';
    $00002021 : result := 'PTP not camera supported SDK version';
    $0000A001 : result := 'PTP vendor unknown command';
    $0000A005 : result := 'PTP vendor operation refused';
    $0000A006 : result := 'PTP vendor lenc cover close';
    $0000A101 : result := 'PTP vendor low battery';
    $0000A102 : result := 'PTP vendor object not ready';
    $0000A104 : result := 'PTP vendor cannot make object';
    $0000A106 : result := 'PTP vendor memorystatus not ready';
    $00008D01 : result := 'Take picture error, focus failed';
    $00008D02 : result := 'Take picture error, reserved';
    $00008D03 : result := 'Take picture error, currently configuring mirror up';
    $00008D04 : result := 'Take picture error, scurrently cleaning sensor';
    $00008D05 : result := 'Take picture error, currently performing silent operations';
    $00008D06 : result := 'Take picture error, card not installed';
    $00008D07 : result := 'Take picture error, error writing to card';
    $00008D08 : result := 'Take picture error, card write protected';
    $00008D09 : result := 'Take picture error, movie crop NG';
    $00008D0A : result := 'Take picture error, strobo charge NG';
    $00008D0B : result := 'Take picture error, no lens NG';
    $00008D0C : result := 'Take picture error, special movie mode NG';
    $00008D0D : result := 'Take picture error, prohibit mode NG';
    $000000F5 : result := 'Generic error plus one';
  else
    result := 'Unkown error';
  end;
end;

end.
